### ISSUE TITLE
Adjustment/Attribute Incorrectly Labeled

### ISSUE THREAD

**Issue by TheBigSoda** [HeyOmae/OMA3#1499]
On the Metatype and Attributes page, when you are going to spend points the radio buttons are incorrectly labeled. Adjustment is labeled as Attribute, and Attribute as Adjustment. It seems to pull from the correct pools but is just confusing.

Example:
I have 13 Adjustment points. I click Attribute as the points to spend. I am only allowed to spend points in my Adjustment-valid stats, and spending points pulls from the Adjustment pool correctly.

**Comment by TheBigSoda** [comment]
<img width="1143" alt="Screenshot 2023-07-16 at 6 35 03 PM" src="https://github.com/HeyOmae/OMA3/assets/26878499/f07540d4-b71c-408c-9f03-e1f67b82f0a7">

Example photo. In this, I have only selected "Attribute" and spent points while "Attribute" was selected.

**Comment by dethstrobe** [comment]
@csakip has a fix for this in #1067

If he doesn't get around to fixing the test for it, i'll have a fix for this when I implement buying karma for attributes, as I'll be adding a 3rd radio button then. Will still be a few weeks away though...
