### ISSUE TITLE
Text is difficult to read

### ISSUE THREAD

**Issue by bradcypert** [HeyOmae/OMA3#1588]
First I love the theme and background for the site, but I do find it difficult to read input field labels on that background. Any thoughts on having a "simple" UI toggle or something similar to remove the colorful background? I've just been removing it via devtools so far.

**Comment by dethstrobe** [comment]
There is one actually. There is a theme selector in the nav menu.
<img width="588" alt="Screenshot 2023-09-06 at 8 35 52 PM" src="https://github.com/HeyOmae/OMA3/assets/6279187/11401a3c-2ec1-4298-a83c-5ccc0a8f0c1e">
The default is cyberterminal 3, but there is also mundane, which is a really boring white using material ui default, and nightwatch which is like a inverted mundane for dark mode.

**Comment by bradcypert** [comment]
Ah, the menu works, I just wasn't aware of that.
