### ISSUE TITLE
Download Runner to JSON not formatting correctly

### ISSUE THREAD

**Issue by Jonas-Geiger** [HeyOmae/OMA3#1683]
The "Download JSON" button is formatting the downloaded json string wrongly. It is always adding escape characters, which the reader (the upload function) won't expect. Normally copying the json with the "Copy to Clipboard" function and uploading it works fine.

**Comment by dethstrobe** [comment]
Thanks, for catching this.

**Comment by dethstrobe** [comment]
Fixed in commit be57096
