### ISSUE TITLE
Color Blind / Poor Eyesight sheet

### ISSUE THREAD

**Issue by criticalfault** [HeyOmae/OMA3#1751]
My friend I absolutely love your setup and tools (I've been trying to understand your UI so I can take some pointers from you!) but we gotta get you a "dark mode" or accessible color scheme. Even if its just a toggle, folks with weaker eye sight are going to struggle with it. I'd love to help if you'd like! Just let me know.

-D

**Comment by dethstrobe** [comment]
#1588 outlines how to change themes and also points out which files need to be changed if you do wish to contribute more themes.

If you want to contribute, please do. I'd love the help.
