### ISSUE TITLE
Missing Cyberears?

### ISSUE THREAD

**Issue by tdoobs** [HeyOmae/OMA3#1827]
Hey, I love this tool. Thank you for creating it. I may be blind, but I don't see any cyberear augment? I see all of the optional cyberear mods as separate cyberware augments, but I have to use essence for each that way instead of just the initial cyberear essence cost so each augment can just use cyberear capacity.

Also, I know this is a bigger thing, but I would love an option for variable cyberware grades to adjust the essence and nguyen costs. But like I said, I realize that's a big thing to implement.

Thank you again for creating such a useful tool.

**Comment by dethstrobe** [comment]
Thanks for the catch. Just released a fix for this.

**Comment by dethstrobe** [comment]
Cyberware grades is also planned for...but just need more time to work on it.
